/* global define */
define({
    "data": [
        {
            "_id" : "1",
            "name": "El Volpe",
            "player": "Tom",
            "sex": "Male",
            "race": "Human",
            "class": "Bard",
            "level": "3",
            "alignment": "Neutral Good",
            "age": "18",
            "height": "5' 4\"",
            "weight": "140lb",
            "skills": [
                {"name": "Acrobatics", "total": "+4", "ability": "DEX", "ranks": "1", "additional": [{"name": "Speed less than 30'", "description": "-4 jump"}]},
                {"name": "Appraise", "total": "+5", "ability": "INT", "ranks": "1"},
                {"name": "Bluff", "total": "+9", "ability": "CHA", "ranks": "3"},
                {"name": "Climb", "total": "+3", "ability": "STR", "ranks": "1"},
                {"name": "Diplomacy", "total": "+9", "ability": "CHA", "ranks": "3"},
                {"name": "Disguise", "total": "+7", "ability": "CHA", "ranks": "1"},
                {"name": "Escape Artist", "total": "+4", "ability": "DEX", "ranks": "1"},
                {"name": "Fly", "total": "+0", "ability": "DEX", "ranks": ""},
                {"name": "Handle Animal", "total": "+7", "ability": "CHA", "ranks": ""},
                {"name": "Heal", "total": "+0", "ability": "WIS", "ranks": ""},
                {"name": "Intimidate", "total": "+8", "ability": "CHA", "ranks": "2"},
                {"name": "Knowledge (history)", "total": "+6", "ability": "INT", "ranks": "1"},
                {"name": "Knowledge (local)", "total": "+6", "ability": "INT", "ranks": "1"},
                {"name": "Knowledge (religion)", "total": "+6", "ability": "INT", "ranks": "1"},
                {"name": "Linguistics", "total": "+5", "ability": "INT", "ranks": "1"},
                {"name": "Perception", "total": "+6", "ability": "WIS", "ranks": "3"},
                {"name": "Perform (percussion instruments)", "total": "+7", "ability": "CHA", "ranks": "1"},
                {"name": "Ride", "total": "+0", "ability": "DEX", "ranks": ""},
                {"name": "Sense Motive", "total": "+6", "ability": "WIS", "ranks": "3"},
                {"name": "Sleight of Hand", "total": "+4", "ability": "DEX", "ranks": "1"},
                {"name": "Stealth", "total": "+4", "ability": "DEX", "ranks": "1"},
                {"name": "Survival", "total": "+0", "ability": "WIS", "ranks": ""},
                {"name": "Swim", "total": "-1", "ability": "STR", "ranks": ""},
                {"name": "Use Magic Device", "total": "+7", "ability": "CHA", "ranks": "1"}
            ],
            "abilities": [
                {"name": "Strength", "abbreviation": "STR", "score": "15", "modifier": "+2"},
                {"name": "Dexterity", "abbreviation": "DEX", "score": "16", "modifier": "+3"},
                {"name": "Constitution", "abbreviation": "CON", "score": "13", "modifier": "+1"},
                {"name": "Intelligence", "abbreviation": "INT", "score": "13", "modifier": "+1"},
                {"name": "Wisdom", "abbreviation": "WIS", "score": "11", "modifier": "0"},
                {"name": "Charisma", "abbreviation": "CHA", "score": "17", "modifier": "+3"}
            ]
        },
        {
            "_id" : "2",
            "name": "Sl'lab",
            "player": "Jason",
            "sex": "Male",
            "race": "Half-Orc",
            "class": "Barbarian",
            "level": "3",
            "alignment": "Chaotic Good",
            "age": "17",
            "height": "6' 2\"",
            "weight": "222lb",
            "skills": [
                {"name": "Acrobatics", "total": "+5", "ability": "DEX", "ranks": "2", "additional": [{"name": "Speed greater than 30'", "description": "+4 jump"}]},
                {"name": "Appraise", "total": "+0", "ability": "INT", "ranks": ""},
                {"name": "Bluff", "total": "-2", "ability": "CHA", "ranks": "1"},
                {"name": "Climb", "total": "+6", "ability": "STR", "ranks": "1"},
                {"name": "Craft (traps)", "total": "+2", "ability": "INT", "ranks": "1"},
                {"name": "Diplomacy", "total": "-2", "ability": "CHA", "ranks": ""},
                {"name": "Disguise", "total": "-2", "ability": "CHA", "ranks": ""},
                {"name": "Escape Artist", "total": "+0", "ability": "DEX", "ranks": ""},
                {"name": "Fly", "total": "+0", "ability": "DEX", "ranks": ""},
                {"name": "Heal", "total": "+3", "ability": "WIS", "ranks": "1"},
                {"name": "Intimidate", "total": "+0", "ability": "CHA", "ranks": ""},
                {"name": "Perception", "total": "+6", "ability": "WIS", "ranks": "1"},
                {"name": "Ride", "total": "+0", "ability": "DEX", "ranks": ""},
                {"name": "Sense Motive", "total": "+3", "ability": "WIS", "ranks": "1"},
                {"name": "Stealth", "total": "+0", "ability": "DEX", "ranks": ""},
                {"name": "Survival", "total": "+2", "ability": "WIS", "ranks": ""},
                {"name": "Swim", "total": "+6", "ability": "STR", "ranks": "1"}
            ],
            "abilities": [
                {"name": "Strength", "abbreviation": "STR", "score": "", "modifier": ""},
                {"name": "Dexterity", "abbreviation": "DEX", "score": "", "modifier": ""},
                {"name": "Constitution", "abbreviation": "CON", "score": "", "modifier": ""},
                {"name": "Intelligence", "abbreviation": "INT", "score": "", "modifier": ""},
                {"name": "Wisdom", "abbreviation": "WIS", "score": "", "modifier": ""},
                {"name": "Charisma", "abbreviation": "CHA", "score": "", "modifier": ""}
            ]
        },
        {
            "_id" : "3",
            "name": "Krug",
            "player": "Chris",
            "sex": "Male",
            "race": "Human",
            "class": "Fighter",
            "level": "2",
            "alignment": "True Neutral",
            "age": "18",
            "height": "5' 10\"",
            "weight": "180lb",
            "skills": [
                {"name": "Acrobatics", "total": "-1", "ability": "DEX", "ranks": ""},
                {"name": "Appraise", "total": "-3", "ability": "INT", "ranks": ""},
                {"name": "Bluff", "total": "+0", "ability": "CHA", "ranks": ""},
                {"name": "Climb", "total": "+2", "ability": "STR", "ranks": ""},
                {"name": "Diplomacy", "total": "+0", "ability": "CHA", "ranks": ""},
                {"name": "Disguise", "total": "+0", "ability": "CHA", "ranks": ""},
                {"name": "Escape Artist", "total": "-1", "ability": "DEX", "ranks": ""},
                {"name": "Fly", "total": "-1", "ability": "DEX", "ranks": ""},
                {"name": "Heal", "total": "+1", "ability": "WIS", "ranks": ""},
                {"name": "Intimidate", "total": "+4", "ability": "CHA", "ranks": "1"},
                {"name": "Perception", "total": "+1", "ability": "WIS", "ranks": ""},
                {"name": "Ride", "total": "+3", "ability": "DEX", "ranks": "1"},
                {"name": "Sense Motive", "total": "+1", "ability": "WIS", "ranks": ""},
                {"name": "Stealth", "total": "-1", "ability": "DEX", "ranks": ""},
                {"name": "Survival", "total": "+5", "ability": "WIS", "ranks": "1"},
                {"name": "Swim", "total": "+2", "ability": "STR", "ranks": ""}
            ],
            "abilities": [
                {"name": "Strength", "abbreviation": "STR", "score": "", "modifier": ""},
                {"name": "Dexterity", "abbreviation": "DEX", "score": "", "modifier": ""},
                {"name": "Constitution", "abbreviation": "CON", "score": "", "modifier": ""},
                {"name": "Intelligence", "abbreviation": "INT", "score": "", "modifier": ""},
                {"name": "Wisdom", "abbreviation": "WIS", "score": "", "modifier": ""},
                {"name": "Charisma", "abbreviation": "CHA", "score": "", "modifier": ""}
            ]
        },
        {
            "_id" : "4",
            "name": "Gandor",
            "player": "Sug",
            "sex": "Male",
            "race": "Human",
            "class": "Wizard",
            "level": "3",
            "alignment": "Chaotic Good",
            "age": "18",
            "height": "5' 4\"",
            "weight": "140lb",
            "skills": [
                {"name": "Acrobatics", "total": "2+", "ability": "DEX", "ranks": ""},
                {"name": "Appraise", "total": "+2", "ability": "INT", "ranks": ""},
                {"name": "Bluff", "total": "+0", "ability": "CHA", "ranks": ""},
                {"name": "Climb", "total": "+3", "ability": "STR", "ranks": "2"},
                {"name": "Diplomacy", "total": "+2", "ability": "CHA", "ranks": "2"},
                {"name": "Disguise", "total": "+1", "ability": "CHA", "ranks": "1"},
                {"name": "Escape Artist", "total": "+2", "ability": "DEX", "ranks": ""},
                {"name": "Fly", "total": "+2", "ability": "DEX", "ranks": ""},
                {"name": "Heal", "total": "+3", "ability": "WIS", "ranks": "2"},
                {"name": "Intimidate", "total": "+0", "ability": "CHA", "ranks": ""},
                {"name": "Knowledge (arcana)", "total": "+7", "ability": "INT", "ranks": "1"},
                {"name": "Knowledge (dungeoneering)", "total": "+7", "ability": "INT", "ranks": "1"},
                {"name": "Knowledge (local)", "total": "+7", "ability": "INT", "ranks": "1"},
                {"name": "Knowledge (nature)", "total": "+7", "ability": "INT", "ranks": "1"},
                {"name": "Perception", "total": "+1", "ability": "WIS", "ranks": ""},
                {"name": "Ride", "total": "+2", "ability": "DEX", "ranks": ""},
                {"name": "Sense Motive", "total": "+2", "ability": "WIS", "ranks": "1"},
                {"name": "Spellcraft", "total": "+8", "ability": "INT", "ranks": "2"},
                {"name": "Stealth", "total": "+4", "ability": "DEX", "ranks": "2"},
                {"name": "Survival", "total": "+2", "ability": "WIS", "ranks": ""},
                {"name": "Swim", "total": "+1", "ability": "STR", "ranks": ""}
            ],
            "abilities": [
                {"name": "Strength", "abbreviation": "STR", "score": "", "modifier": ""},
                {"name": "Dexterity", "abbreviation": "DEX", "score": "", "modifier": ""},
                {"name": "Constitution", "abbreviation": "CON", "score": "", "modifier": ""},
                {"name": "Intelligence", "abbreviation": "INT", "score": "", "modifier": ""},
                {"name": "Wisdom", "abbreviation": "WIS", "score": "", "modifier": ""},
                {"name": "Charisma", "abbreviation": "CHA", "score": "", "modifier": ""}
            ]
        },
        {
            "_id" : "5",
            "name": "Baltok",
            "player": "Dean",
            "sex": "Male",
            "race": "Dwarf",
            "class": "Cleric",
            "level": "3",
            "alignment": "Chaotic Neutral",
            "age": "51",
            "height": "4'",
            "weight": "164lb",
            "skills": [
                {"name": "Acrobatics", "total": "-3", "ability": "DEX", "ranks": "", "additional": [{"name": "Belt of tumbling", "description": "+4 competence bonus to move through a threatened square or enemy's space"}, {"name": "Speed less than 30'", "description": "-4 jump"}]},
                {"name": "Appraise", "total": "-1", "ability": "INT", "ranks": "", "additional": [{"name": "Greed", "description": "+2 to determine the price of nonmagic items with precious metals or gemstones"}]},
                {"name": "Bluff", "total": "+1", "ability": "CHA", "ranks": "1"},
                {"name": "Climb", "total": "-1", "ability": "STR", "ranks": "1"},
                {"name": "Diplomacy", "total": "+0", "ability": "CHA", "ranks": ""},
                {"name": "Disguise", "total": "+0", "ability": "CHA", "ranks": ""},
                {"name": "Escape Artist", "total": "-3", "ability": "DEX", "ranks": ""},
                {"name": "Fly", "total": "-3", "ability": "DEX", "ranks": ""},
                {"name": "Heal", "total": "+8", "ability": "WIS", "ranks": "1"},
                {"name": "Intimidate", "total": "+0", "ability": "CHA", "ranks": ""},
                {"name": "Knowledge (religion)", "total": "+3", "ability": "INT)", "ranks": "1"},
                {"name": "Perception", "total": "+4", "ability": "WIS", "ranks": "", "additional": [{"name": "Stonecutting", "description": "+2 racial bonus to notice unusual stonework"}]},
                {"name": "Ride", "total": "-3", "ability": "DEX", "ranks": ""},
                {"name": "Sense Motive", "total": "+8", "ability": "WIS", "ranks": "1"},
                {"name": "Spellcraft", "total": "+3", "ability": "INT", "ranks": "1"},
                {"name": "Stealth", "total": "-3", "ability": "DEX", "ranks": ""},
                {"name": "Survival", "total": "+4", "ability": "WIS", "ranks": ""},
                {"name": "Swim", "total": "-2", "ability": "STR", "ranks": ""}
            ],
            "abilities": [
                {"name": "Strength", "abbreviation": "STR", "score": "", "modifier": ""},
                {"name": "Dexterity", "abbreviation": "DEX", "score": "", "modifier": ""},
                {"name": "Constitution", "abbreviation": "CON", "score": "", "modifier": ""},
                {"name": "Intelligence", "abbreviation": "INT", "score": "", "modifier": ""},
                {"name": "Wisdom", "abbreviation": "WIS", "score": "", "modifier": ""},
                {"name": "Charisma", "abbreviation": "CHA", "score": "", "modifier": ""}
            ]
        },
        {
            "_id" : "6",
            "name": "Dorion",
            "player": "Mike",
            "sex": "Male",
            "race": "Dwarf",
            "class": "Fighter",
            "level": "3",
            "alignment": "Chaotic Neutral",
            "age": "58",
            "height": "4' 1\"",
            "weight": "178lb",
            "skills": [
                {"name": "Acrobatics", "total": "-6", "ability": "DEX", "ranks": "", "additional": [{"name": "Speed less than 30'", "description": "-4 jump"}]},
                {"name": "Appraise", "total": "-1", "ability": "INT", "ranks": "", "additional": [{"name": "Greed", "description": "+2 to determine the price of nonmagic items with precious metals or gemstones"}]},
                {"name": "Bluff", "total": "-1", "ability": "CHA", "ranks": ""},
                {"name": "Climb", "total": "-2", "ability": "STR", "ranks": "1"},
                {"name": "Diplomacy", "total": "-1", "ability": "CHA", "ranks": ""},
                {"name": "Disguise", "total": "-1", "ability": "CHA", "ranks": ""},
                {"name": "Escape Artist", "total": "-6", "ability": "DEX", "ranks": ""},
                {"name": "Fly", "total": "-6", "ability": "DEX", "ranks": ""},
                {"name": "Heal", "total": "+1", "ability": "WIS", "ranks": ""},
                {"name": "Intimidate", "total": "+4", "ability": "CHA", "ranks": "2"},
                {"name": "Knowledge (engineering)", "total": "+4", "ability": "INT", "ranks": "1"},
                {"name": "Perception", "total": "+1", "ability": "WIS", "ranks": "", "additional": [{"name": "Stonecutting", "description": "+2 bonus to notice unusual stonework, such as traps and hidden doors in stone walls or floors"}]},
                {"name": "Ride", "total": "-2", "ability": "DEX", "ranks": "1"},
                {"name": "Sense Motive", "total": "+1", "ability": "WIS", "ranks": ""},
                {"name": "Stealth", "total": "-6", "ability": "DEX", "ranks": ""},
                {"name": "Survival", "total": "+5", "ability": "WIS", "ranks": "1"},
                {"name": "Swim", "total": "-6", "ability": "STR", "ranks": ""}
            ],
            "abilities": [
                {"name": "Strength", "abbreviation": "STR", "score": "", "modifier": ""},
                {"name": "Dexterity", "abbreviation": "DEX", "score": "", "modifier": ""},
                {"name": "Constitution", "abbreviation": "CON", "score": "", "modifier": ""},
                {"name": "Intelligence", "abbreviation": "INT", "score": "", "modifier": ""},
                {"name": "Wisdom", "abbreviation": "WIS", "score": "", "modifier": ""},
                {"name": "Charisma", "abbreviation": "CHA", "score": "", "modifier": ""}
            ]
        },
        {
            "_id" : "7",
            "name": "Bellamin",
            "player": "Ben",
            "sex": "Male",
            "race": "Halfling",
            "class": "Rogue",
            "level": "3",
            "alignment": "Chaotic Neutral",
            "age": "25",
            "height": "2' 11\"",
            "weight": "30lb",
            "skills": [
                {"name": "Acrobatics", "total": "", "ability": "DEX", "ranks": ""},
                {"name": "Appraise", "total": "", "ability": "INT", "ranks": ""},
                {"name": "Bluff", "total": "", "ability": "CHA", "ranks": ""},
                {"name": "Climb", "total": "", "ability": "STR", "ranks": ""},
                {"name": "Diplomacy", "total": "", "ability": "CHA", "ranks": ""},
                {"name": "Disguise", "total": "", "ability": "CHA", "ranks": ""},
                {"name": "Escape Artist", "total": "", "ability": "DEX", "ranks": ""},
                {"name": "Fly", "total": "", "ability": "DEX", "ranks": ""},
                {"name": "Heal", "total": "", "ability": "WIS", "ranks": ""},
                {"name": "Intimidate", "total": "", "ability": "CHA", "ranks": ""},
                {"name": "Perception", "total": "", "ability": "WIS", "ranks": ""},
                {"name": "Ride", "total": "", "ability": "DEX", "ranks": ""},
                {"name": "Sense Motive", "total": "", "ability": "WIS", "ranks": ""},
                {"name": "Stealth", "total": "", "ability": "DEX", "ranks": ""},
                {"name": "Survival", "total": "", "ability": "WIS", "ranks": ""},
                {"name": "Swim", "total": "", "ability": "STR", "ranks": ""}
            ],
            "abilities": [
                {"name": "Strength", "abbreviation": "STR", "score": "", "modifier": ""},
                {"name": "Dexterity", "abbreviation": "DEX", "score": "", "modifier": ""},
                {"name": "Constitution", "abbreviation": "CON", "score": "", "modifier": ""},
                {"name": "Intelligence", "abbreviation": "INT", "score": "", "modifier": ""},
                {"name": "Wisdom", "abbreviation": "WIS", "score": "", "modifier": ""},
                {"name": "Charisma", "abbreviation": "CHA", "score": "", "modifier": ""}
            ]
        },
        {
            "_id" : "8",
            "name": "Leithiandir",
            "player": "Abhi",
            "sex": "Male",
            "race": "Elf",
            "class": "Rogue",
            "level": "3",
            "alignment": "Chaotic Neutral",
            "age": "124",
            "height": "6' 1\"",
            "weight": "117lb",
            "skills": [
                {"name": "Acrobatics", "total": "", "ability": "DEX", "ranks": ""},
                {"name": "Appraise", "total": "", "ability": "INT", "ranks": ""},
                {"name": "Bluff", "total": "", "ability": "CHA", "ranks": ""},
                {"name": "Climb", "total": "", "ability": "STR", "ranks": ""},
                {"name": "Diplomacy", "total": "", "ability": "CHA", "ranks": ""},
                {"name": "Disguise", "total": "", "ability": "CHA", "ranks": ""},
                {"name": "Escape Artist", "total": "", "ability": "DEX", "ranks": ""},
                {"name": "Fly", "total": "", "ability": "DEX", "ranks": ""},
                {"name": "Heal", "total": "", "ability": "WIS", "ranks": ""},
                {"name": "Intimidate", "total": "", "ability": "CHA", "ranks": ""},
                {"name": "Perception", "total": "", "ability": "WIS", "ranks": ""},
                {"name": "Ride", "total": "", "ability": "DEX", "ranks": ""},
                {"name": "Sense Motive", "total": "", "ability": "WIS", "ranks": ""},
                {"name": "Stealth", "total": "", "ability": "DEX", "ranks": ""},
                {"name": "Survival", "total": "", "ability": "WIS", "ranks": ""},
                {"name": "Swim", "total": "", "ability": "STR", "ranks": ""}
            ],
            "abilities": [
                {"name": "Strength", "abbreviation": "STR", "score": "", "modifier": ""},
                {"name": "Dexterity", "abbreviation": "DEX", "score": "", "modifier": ""},
                {"name": "Constitution", "abbreviation": "CON", "score": "", "modifier": ""},
                {"name": "Intelligence", "abbreviation": "INT", "score": "", "modifier": ""},
                {"name": "Wisdom", "abbreviation": "WIS", "score": "", "modifier": ""},
                {"name": "Charisma", "abbreviation": "CHA", "score": "", "modifier": ""}
            ]
        },
        {
            "_id" : "9",
            "name": "Miitya",
            "player": "Andrew",
            "sex": "Male",
            "race": "Half-Elf",
            "class": "Ranger",
            "level": "3",
            "alignment": "",
            "age": "",
            "height": "",
            "weight": "",
            "skills": [
                {"name": "Acrobatics", "total": "", "ability": "DEX", "ranks": ""},
                {"name": "Appraise", "total": "", "ability": "INT", "ranks": ""},
                {"name": "Bluff", "total": "", "ability": "CHA", "ranks": ""},
                {"name": "Climb", "total": "", "ability": "STR", "ranks": ""},
                {"name": "Diplomacy", "total": "", "ability": "CHA", "ranks": ""},
                {"name": "Disguise", "total": "", "ability": "CHA", "ranks": ""},
                {"name": "Escape Artist", "total": "", "ability": "DEX", "ranks": ""},
                {"name": "Fly", "total": "", "ability": "DEX", "ranks": ""},
                {"name": "Heal", "total": "", "ability": "WIS", "ranks": ""},
                {"name": "Intimidate", "total": "", "ability": "CHA", "ranks": ""},
                {"name": "Perception", "total": "", "ability": "WIS", "ranks": ""},
                {"name": "Ride", "total": "", "ability": "DEX", "ranks": ""},
                {"name": "Sense Motive", "total": "", "ability": "WIS", "ranks": ""},
                {"name": "Stealth", "total": "", "ability": "DEX", "ranks": ""},
                {"name": "Survival", "total": "", "ability": "WIS", "ranks": ""},
                {"name": "Swim", "total": "", "ability": "STR", "ranks": ""}
            ],
            "abilities": [
                {"name": "Strength", "abbreviation": "STR", "score": "", "modifier": ""},
                {"name": "Dexterity", "abbreviation": "DEX", "score": "", "modifier": ""},
                {"name": "Constitution", "abbreviation": "CON", "score": "", "modifier": ""},
                {"name": "Intelligence", "abbreviation": "INT", "score": "", "modifier": ""},
                {"name": "Wisdom", "abbreviation": "WIS", "score": "", "modifier": ""},
                {"name": "Charisma", "abbreviation": "CHA", "score": "", "modifier": ""}
            ]
        },
        {
            "_id" : "10",
            "name": "Loki",
            "player": "Joe",
            "sex": "Male",
            "race": "Half-Elf",
            "class": "Druid",
            "level": "2",
            "alignment": "True Neutral",
            "age": "24",
            "height": "5' 9\"",
            "weight": "135lb",
            "skills": [
                {"name": "Acrobatics", "total": "", "ability": "DEX", "ranks": ""},
                {"name": "Appraise", "total": "", "ability": "INT", "ranks": ""},
                {"name": "Bluff", "total": "", "ability": "CHA", "ranks": ""},
                {"name": "Climb", "total": "", "ability": "STR", "ranks": ""},
                {"name": "Diplomacy", "total": "", "ability": "CHA", "ranks": ""},
                {"name": "Disguise", "total": "", "ability": "CHA", "ranks": ""},
                {"name": "Escape Artist", "total": "", "ability": "DEX", "ranks": ""},
                {"name": "Fly", "total": "", "ability": "DEX", "ranks": ""},
                {"name": "Heal", "total": "", "ability": "WIS", "ranks": ""},
                {"name": "Intimidate", "total": "", "ability": "CHA", "ranks": ""},
                {"name": "Perception", "total": "", "ability": "WIS", "ranks": ""},
                {"name": "Ride", "total": "", "ability": "DEX", "ranks": ""},
                {"name": "Sense Motive", "total": "", "ability": "WIS", "ranks": ""},
                {"name": "Stealth", "total": "", "ability": "DEX", "ranks": ""},
                {"name": "Survival", "total": "", "ability": "WIS", "ranks": ""},
                {"name": "Swim", "total": "", "ability": "STR", "ranks": ""}
            ],
            "abilities": [
                {"name": "Strength", "abbreviation": "STR", "score": "", "modifier": ""},
                {"name": "Dexterity", "abbreviation": "DEX", "score": "", "modifier": ""},
                {"name": "Constitution", "abbreviation": "CON", "score": "", "modifier": ""},
                {"name": "Intelligence", "abbreviation": "INT", "score": "", "modifier": ""},
                {"name": "Wisdom", "abbreviation": "WIS", "score": "", "modifier": ""},
                {"name": "Charisma", "abbreviation": "CHA", "score": "", "modifier": ""}
            ]
        }
    ]
});